/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_thales_ScreenLockDetect */

#ifndef _Included_at_thales_ScreenLockDetect
#define _Included_at_thales_ScreenLockDetect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_thales_ScreenLockDetect
 * Method:    isScreenLocked
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_at_thales_ScreenLockDetect_isScreenLocked
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
